version: '3'
services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 8080:80
        volumes:
            - ./html:/var/www/html
            - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php.ini:/usr/local/etc/php/php.ini
        links:
            - 'mariadb'
    mariadb:
        image: mariadb:10.5
        ports:
            - 8085:3306
        volumes:
            - mariadb:/var/lib/mysql
            - ./mariadb/my.cnf:/etc/mysql/my.cnf
        environment:
            TZ: "Europe/Madrid"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "database_root_pas"
            MYSQL_USER: 'database_user'
            MYSQL_PASSWORD: 'database_pass'
            MYSQL_DATABASE: 'database_name'
volumes:
    mariadb:
